name-template: '$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
prerelease: false
categories:
  - title: 🚀 Improvements
    labels:
      - enhancement
  - title: 🐛 Bug Fixes
    labels:
      - bug
  - title: 📝 Documentation
    label: documentation
  - title: 👻 Maintenance
    labels:
      - chore
      - refactoring
  - title: 📦 Dependency updates
    collapse-after: 2
    labels:
      - dependencies
exclude-labels:
  - invalid
  - skip-changelog
  - reverted
# Exclude specific usernames from the generated $CONTRIBUTORS variable.
# https://github.com/release-drafter/release-drafter/tree/master#exclude-contributors
exclude-contributors:
    - 'dependabot'
    - 'dependabot[bot]'
template: |
  **TODO: add a short description about the release content - important for url preview**
  This new release focuses on .... **or something similar**

  **TODO: review the contributors list (remove ALL bots and avoid duplicates)**
  Thanks to all the contributors of this release 🌈: $CONTRIBUTORS

  **TODO: check previous and next tag in the "full changelog" link in the "What's changed section"**

  # Highlights

  **TODO: add screenshots and user oriented info**

  # What's Changed

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$NEXT_PATCH_VERSION

  $CHANGES
