name: 'Update files of R package with a new version'
description: 'You can customize the current version and the type of version updating'
inputs:
  UPDATE_TYPE:
    description: 'The new version type [major | minor | patch]'
    required: true
    default: 'patch'
  CURRENT_VERSION:
    description: 'The current version'
    required: true
  OUTPUT_NAME:
    description: 'The name of the variable as output of this action'
    required: true
  NEXT_VERSION_COMMIT_TYPE:
    description: 'The type of the next version to add on the commit message'
    required: false

runs:
  using: "composite"
  steps:
    - name: Generate new version
      id: next_version
      uses: leovs09/semver-release-action@v1
      with:
        bump: ${{ inputs.UPDATE_TYPE }}
        version: ${{ inputs.CURRENT_VERSION }}
        github_token: ${{ secrets.GH_RELEASE_TOKEN }}
        dry_run: true

    - name: Update README.md with ${{ steps.next_version.outputs.version }}
      run: |-
        sed -i -E 's/${{ inputs.CURRENT_VERSION }}/${{ steps.next_version.outputs.version }}/g' README.md

    - name: Update DESCRIPTION with ${{ steps.next_version.outputs.version }}
      run: |-
        sed -i -E 's/Version: "(.*)"/Version: "${{ steps.next_version.outputs.version }}"/g' DESCRIPTION

    - name: Commit
      run: |
        git add README.md
        git add DESCRIPTION
        git commit -m "[RELEASE] Set the ${{NEXT_VERSION_COMMIT_TYPE}}version to ${{ env.RELEASE_VERSION }}"
        git push

    - name: Set ${{ OUTPUT_NAME }}
      run: echo "${{ OUTPUT_NAME }}=${{ steps.next_version.outputs.version }}" >> $GITHUB_OUTPUT
