name: 'Build the documentation'
description: 'Build static and API documentation.'

runs:
  using: 'composite'
  steps:
    # The checkout is done in the workflow using this action
    - name: Setup node
      uses: actions/setup-node@v6
      with:
        node-version: '22'
    - name: Install dependencies
      shell: bash
      run: npm ci
    - name: Build docs
      shell: bash
      run: npm run api-doc
    - name: Copy static pages
      shell: bash
      run: cp -r public/docs build
