name: Surge Preview Tools
description: TODO

inputs:
  surge-token:
    description: 'surge.sh token'
    required: false

outputs:
  domain-exist:
    description: 'true if the domain related to the preview-url exists. false otherwise'
  preview-url:
    description: 'The url for the related PR preview, as computed by the surge-preview action'
  should-run:
    description: 'TODO'

runs:
  using: 'node16'
  main: 'dist/index.js'
