name: Surge Preview Tools
description: TODO

inputs:
  surge-token:
    description: 'surge.sh token'
    required: false

outputs:
  should-run:
    description: 'TODO'
  preview-url:
    description: 'The url for the related PR preview, as computed by the surge-preview action'

runs:
  using: 'node16'
  main: 'dist/index.js'
