name: Send a message on Twitter & Discord
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version to announce'
        type: string
        required: true
      description:
        description: 'A short description of the version to announce'
        type: string
        required: true

jobs:
  tweet:
    runs-on: ${{ vars.RUNNER_UBUNTU }}
    steps:
      - name: Tweet
        uses: snow-actions/tweet@v1.4.0
        with:
          status: |
            📣 test ${{ github.event.inputs.version }} is out! 🎉
            
            ${{ github.event.inputs.description }}
        
            #bpmnvisualization #bpmn #visualization #typescript #opensource
            ${{ github.server_url }}/${{ github.repository }}/releases/tag/v${{ github.event.inputs.version }}
        env:
          CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          CONSUMER_API_SECRET_KEY: ${{ secrets.TWITTER_CONSUMER_API_SECRET_KEY }}
          ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}

  send-message-on-discord:
    runs-on: ${{ vars.RUNNER_UBUNTU }}
    steps:
      - name: Send a message on Discord
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          nodetail: true
          notimestamp: true
          title: New version of `software` is ready!
          url: ${{ github.server_url }}/${{ github.repository }}/releases/tag/v${{ github.event.inputs.version }}
          description: |
            📣 test ${{ github.event.inputs.version }} is out! 🎉
            
            ${{ github.event.inputs.description }}
          color: 0xAFEEEE