name: Execute depending on secrets availability
on:
  pull_request:
    branches:
      - master


jobs:
  # This is skipped when triggered from forked repositories or involving Dependabot
  conditional_when_secret_available:
    if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch' )
    runs-on: ubuntu-20.04
    steps:
      - name: Message
        run: echo "I have been triggered because the secret is available"

  conditional_never_run_as_secret_not_available:
    if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch' )
    runs-on: ubuntu-20.04
    steps:
      - name: Message
        run: echo "I have been triggered because the secret is available"
#        TODO fail the build
