name: Execute depending on secrets availability
on:
  pull_request:
    branches:
      - master


jobs:
  always_run:
    runs-on: ubuntu-20.04
    steps:
      - name: Message
        run: echo "I always run!"

  # Should always run
  secret_always_available:
    if: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-20.04
    steps:
      - name: Message
        run: echo "I have been triggered because the secret is available"

  # This is skipped when triggered from forked repositories or involving Dependabot
  conditional_when_secret_available:
    if: ${{ secrets.GH_RELEASE_TOKEN }}
    runs-on: ubuntu-20.04
    steps:
      - name: Message
        run: echo "I have been triggered because the secret is available"

  conditional_when_secret_available_alternative_syntax:
    if: ${{ secrets.GH_RELEASE_TOKEN != '' }}
    runs-on: ubuntu-20.04
    steps:
      - name: Message
        run: echo "I have been triggered because the secret is available"

# ${{ secrets.TEST_UNAVAILABLE_SECRET != '' }}
  conditional_never_run_as_secret_not_available:
    if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch' )
    runs-on: ubuntu-20.04
    steps:
      - name: Message
        run: echo "I have been triggered because the secret is available"
#        TODO fail the build
