name: Manage Surge Deployments
on:
  workflow_dispatch:
#    inputs:
#      type:
#        description: 'New version type [new-version | major | minor | patch]'
#        required: true
#        default: 'patch'

jobs:
  list_deployments:
    runs-on: ubuntu-20.04
    steps:
      - name: List deployments
        run: |
          npx surge list --token "${{ secrets.SURGE_TOKEN }}"
