name: Surge PR Preview - Upload Stage

on:
  workflow_run:
    workflows: ["Surge PR Preview - Build Stage"]
    types:
      - completed

permissions:
  pull-requests: write # surge-preview creates or updates PR comments about the deployment status

jobs:
  upload-preview:
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: download dist artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          name: pr-build-dist
          path: site/
      - name: Debug step
        run: |
          echo "workflow_run: ${{toJSON(github.event.workflow_run)}}"
          echo "workflow_run.head_sha: ${{github.event.workflow_run.head_sha}}"

      - name: deploy to Surge
        uses: afc163/surge-preview@v1
        with:
          surge_token: ${{ secrets.SURGE_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build: echo done
          dist: site
