name: Manage Surge Deployments
on:
  workflow_dispatch:
    inputs:
      teardown:
        description: 'If true, perform a deployment teardown. Otherwise, list deployments'
        required: true
        type: boolean
        default: false
      deployment-url:
        description: 'Url of the deployment to teardown.'
        required: false

jobs:
  list_deployments:
    if: github.event.inputs.teardown != 'true'
    runs-on: ubuntu-22.04
    steps:
      - name: List deployments
        run: |
          npx surge --token ${{ secrets.SURGE_TOKEN }} list

  teardown_deployments:
    if: github.event.inputs.teardown == 'true'
    runs-on: ubuntu-22.04
    steps:
      - name: Teardown deployments
        run: |
          npx surge --token ${{ secrets.SURGE_TOKEN }} teardown ${{ github.event.inputs.deployment-url }}
