name: Upload Demo Archive & Trigger Examples Repository Update

on:
  push:
    tags:
      -  v*

jobs:
  upload_demo_archive:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        run: echo "Done"
      - name: Install dependencies
        run: echo "Done"
      - name: Build Demo
        run: echo ${{ steps.get_version.outputs.VERSION }}
      - name: Upload Demo
        uses: actions/upload-artifact@v3
        with:
          name: demo-${{github.sha}}
          path: LICENSE
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v*}
      - name: Send Repository Dispatch event
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GH_RELEASE_TOKEN }}
          repository: process-analytics/github-actions-playground
          event-type: update_bpmn_visualization_version
          client-payload: '{
              "build_demo_repo": "${{ github.repository }}",
              "build_demo_workflow_id": "upload-demo-archive-and-trigger-examples-repository-update.yml",
              "artifact_name": "demo-${{ github.sha }}",
              "version": "${{ steps.get_version.outputs.VERSION }}"
            }'