name: Workflow Dispatch branch detection
on:
  workflow_dispatch:
  # TODO remove when setup
  pull_request:

# define concurrency setting for this workflow only
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow
concurrency: ${{ github.workflow }}

jobs:
  slow1:
    runs-on: ubuntu-20.04
    env:
      WAIT_TIME: 40
    steps:
      - name: Simulate slow processing 1.1
        run: sleep ${WAIT_TIME}
      - name: Simulate slow processing 1.2
        run: sleep ${WAIT_TIME}
  slow2:
    runs-on: ubuntu-22.04
    env:
      WAIT_TIME: 50
    steps:
      - name: Simulate slow processing 2.1
        run: sleep ${WAIT_TIME}
      - name: Simulate slow processing 2.2
        run: sleep ${WAIT_TIME}
